### ISSUE TITLE
"error generating the keys" 

### ISSUE THREAD

**Issue by kravietz** [Criptext/Criptext-Email-React-Client#1073]
**Describe the bug**
Criptext app on Linux fails sign-up due to "error generating the keys" 

**To Reproduce**
1. Download latest AppImage on Ubuntu 19
2. chmod +x, run the AppImage
3. Select Sign Up on the login screen
4. Fill in the basic details (username, password etc), click Sign Up
5. An error is displayed "error generating the keys", when clicking Retry the same thing happens all over again

**Expected behavior**
Complete sign up process

**Screenshots (Optional)**
![2019-07-18_13-23](https://user-images.githubusercontent.com/616047/61457000-f12c3a80-a956-11e9-8b4a-3105ab558d08.png)

**Device and System information (please complete the following information):**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

**Additional information**

**Comment by erikaperugachi** [comment]
https://github.com/Criptext/Criptext-Email-React-Client/issues/1075
