### ISSUE TITLE
Cyrillic letters shown in wrong font

### ISSUE THREAD

**Issue by rizhenkov** [Criptext/Criptext-Email-React-Client#1130]
Look like you are using fonts that do not support cyrillic symbols.

**Expected behavior**
Cyrillic letters must be at least sans-serif (use fallback system fonts at css). 
`font-family:"My Font Without Cyr", sans-serif;`

But better if you will use font [with cyrillic letters](https://fonts.google.com/?subset=cyrillic).

**Screenshots (Optional)**
![изображение](https://user-images.githubusercontent.com/987517/63005412-24de7f80-be85-11e9-9c2c-0f69bd4792af.png)

**Device and System information (please complete the following information):**
* OS Version: Windows 10 1903 b. 18362.239
* App Version: 0.23.00

**Comment by rizhenkov** [comment]
@erikaperugachi Really quick fix! Thank you!
I will test it after next version rolling out (do not have ability to build from sources)

**Comment by erikaperugachi** [comment]
> @erikaperugachi Really quick fix! Thank you!
> I will test it after next version rolling out (do not have ability to build from sources)

I will update the README with that. Thanks for your comments!
