### ISSUE TITLE
Critical bug: client does not allow letters to some real emails!

### ISSUE THREAD

**Issue by rizhenkov** [Criptext/Criptext-Email-React-Client#1164]
![image](https://user-images.githubusercontent.com/987517/64605539-0066bc00-d3cd-11e9-8880-083452de9714.png)

If I use email at ".finance" domain client does not allow to send letter (Send button inactive).

Solution must be not only whitelisting that domain. It need to be compatible with RFC 5322 specification. 

More info and correct regex for validation see here: http://emailregex.com/

**Comment by rizhenkov** [comment]
@erikaperugachi What do you think?

**Comment by erikaperugachi** [comment]
> @erikaperugachi What do you think?

We will fix that!
