### ISSUE TITLE
Fails to start in Ubuntu 18.04 and 18.10

### ISSUE THREAD

**Issue by logix2** [Criptext/Criptext-Email-React-Client#476]
I tried the desktop application (AppImage) on Ubuntu 18.04 and 18.10, and when trying to create a new account, it fails on the key generation step with the following error being displayed:

```
Uncaught Exception:
Error: Cannot find module './../dataTransferClient'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/tmp/.mount_CripteeKT6or/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at BrowserWindow.loadingWindow.on (/tmp/.mount_CripteeKT6or/resources/app.asar/src/windows/loading.js:29:26)
    at emitOne (events.js:115:13)
    at BrowserWindow.emit (events.js:210:7)
```

To reproduce this, use Ubuntu 18.04, run the Criptext desktop application and attempt to create a new account. After entering all the account details an error will be displayed, saying that it can't generate the keys.

I'm not sure what the Criptext version is because I couldn't actually use the app. Also, the AppImage filename doesn't mention the application version so all I can say about the version is that I downladed it today from https://criptext.com/

Let me know if you need anything else.

**Comment by GAumala** [comment]
Hi! Thanks for filing an issue. We are aware of the error and are currently working on a patch. 

Some people have reported that trying multiple times works around the issue. But it's probably better to wait for a new release later today or tomorrow.

**Comment by JulianAdams4** [comment]
Hi @logix2!
First of all, thanks for reporting this issue.
We detected that the error occurred when trying to clean temporary files during the Link devices and Login / Signup process
We have already fixed this error and it will be available very soon in the next release.
